# https://github.com/Julian/jsonschema
# Example of validating the output json generated by the stanza plugin.
from jsonschema import validate

# A sample schema, like what we'd get from json.load()
schema = {
    "type": "array",
    "properties": {
        "_id": {"type": "number"},
        "text": {"type": "string"},
        "annotation": {"type": "array"},
    },
}

# If no exception is raised by validate(), the instance is valid.
result = validate(
    instance=[
  {
    '_id': 1,
    'text': 'I went to the bank to deposit my money .',
    'annotation': [
      {
        'idx': 0,
        'text': 'I',
        'pos': 'PRON',
        'tag': 'PRP',
        'shape': 'X',
        'is_alpha': True,
        'is_title': True,
        'like_num': False
      },
      {
        'idx': 1,
        'text': 'went',
        'pos': 'VERB',
        'tag': 'VBD',
        'shape': 'xxxx',
        'is_alpha': True,
        'is_title': False,
        'like_num': False
      },
      {
        'idx': 2,
        'text': 'to',
        'pos': 'ADP',
        'tag': 'IN',
        'shape': 'xx',
        'is_alpha': True,
        'is_title': False,
        'like_num': False
      },
      {
        'idx': 3,
        'text': 'the',
        'pos': 'DET',
        'tag': 'DT',
        'shape': 'xxx',
        'is_alpha': True,
        'is_title': False,
        'like_num': False
      },
      {
        'idx': 4,
        'text': 'bank',
        'pos': 'NOUN',
        'tag': 'NN',
        'shape': 'xxxx',
        'is_alpha': True,
        'is_title': False,
        'like_num': False
      },
      {
        'idx': 5,
        'text': 'to',
        'pos': 'PART',
        'tag': 'TO',
        'shape': 'xx',
        'is_alpha': True,
        'is_title': False,
        'like_num': False
      },
      {
        'idx': 6,
        'text': 'deposit',
        'pos': 'VERB',
        'tag': 'VB',
        'shape': 'xxxx',
        'is_alpha': True,
        'is_title': False,
        'like_num': False
      },
      {
        'idx': 7,
        'text': 'my',
        'pos': 'DET',
        'tag': 'PRP$',
        'shape': 'xx',
        'is_alpha': True,
        'is_title': False,
        'like_num': False
      },
      {
        'idx': 8,
        'text': 'money',
        'pos': 'NOUN',
        'tag': 'NN',
        'shape': 'xxxx',
        'is_alpha': True,
        'is_title': False,
        'like_num': False
      },
      {
        'idx': 9,
        'text': '.',
        'pos': 'PUNCT',
        'tag': '.',
        'shape': '.',
        'is_alpha': False,
        'is_title': False,
        'like_num': False
      }
    ],
    'noun_chunks': [
      {
        'text': 'I',
        'root_text': 'I',
        'root_dep_': 'nsubj',
        'root_head_text': 'went'
      },
      {
        'text': 'the bank',
        'root_text': 'bank',
        'root_dep_': 'pobj',
        'root_head_text': 'to'
      },
      {
        'text': 'my money',
        'root_text': 'money',
        'root_dep_': 'dobj',
        'root_head_text': 'deposit'
      }
    ]
  }
],
    schema=schema,
)
print(result)  # YES None
