# https://github.com/Julian/jsonschema
# Example of validating the output json generated by the stanza plugin.
from jsonschema import validate

# A sample schema, like what we'd get from json.load()
schema = {
    "type": "array",
    "properties": {
        "_id": {"type": "number"},
        "text": {"type": "string"},
        "annotation": {"type": "array"},
    },
}

# If no exception is raised by validate(), the instance is valid.
result = validate(
    instance=[
        {
            "_id": 1,
            "text": "I went to the bank to deposit my money .",
            "annotation": [
                {
                    "id": "1",
                    "text": "I",
                    "lemma": "I",
                    "upos": "PRON",
                    "xpos": "PRP",
                    "feats": "Case=Nom|Number=Sing|Person=1|PronType=Prs",
                    "head": 2,
                    "deprel": "nsubj",
                    "misc": "start_char=0|end_char=1",
                },
                {
                    "id": "2",
                    "text": "went",
                    "lemma": "go",
                    "upos": "VERB",
                    "xpos": "VBD",
                    "feats": "Mood=Ind|Tense=Past|VerbForm=Fin",
                    "head": 0,
                    "deprel": "root",
                    "misc": "start_char=2|end_char=6",
                },
                {
                    "id": "3",
                    "text": "to",
                    "lemma": "to",
                    "upos": "ADP",
                    "xpos": "IN",
                    "head": 5,
                    "deprel": "case",
                    "misc": "start_char=7|end_char=9",
                },
                {
                    "id": "4",
                    "text": "the",
                    "lemma": "the",
                    "upos": "DET",
                    "xpos": "DT",
                    "feats": "Definite=Def|PronType=Art",
                    "head": 5,
                    "deprel": "det",
                    "misc": "start_char=10|end_char=13",
                },
                {
                    "id": "5",
                    "text": "bank",
                    "lemma": "bank",
                    "upos": "NOUN",
                    "xpos": "NN",
                    "feats": "Number=Sing",
                    "head": 2,
                    "deprel": "obl",
                    "misc": "start_char=14|end_char=18",
                },
                {
                    "id": "6",
                    "text": "to",
                    "lemma": "to",
                    "upos": "PART",
                    "xpos": "TO",
                    "head": 7,
                    "deprel": "mark",
                    "misc": "start_char=19|end_char=21",
                },
                {
                    "id": "7",
                    "text": "deposit",
                    "lemma": "deposit",
                    "upos": "VERB",
                    "xpos": "VB",
                    "feats": "VerbForm=Inf",
                    "head": 2,
                    "deprel": "advcl",
                    "misc": "start_char=22|end_char=29",
                },
                {
                    "id": "8",
                    "text": "my",
                    "lemma": "my",
                    "upos": "PRON",
                    "xpos": "PRP$",
                    "feats": "Number=Sing|Person=1|Poss=Yes|PronType=Prs",
                    "head": 9,
                    "deprel": "nmod:poss",
                    "misc": "start_char=30|end_char=32",
                },
                {
                    "id": "9",
                    "text": "money",
                    "lemma": "money",
                    "upos": "NOUN",
                    "xpos": "NN",
                    "feats": "Number=Sing",
                    "head": 7,
                    "deprel": "obj",
                    "misc": "start_char=33|end_char=38",
                },
                {
                    "id": "10",
                    "text": ".",
                    "lemma": ".",
                    "upos": "PUNCT",
                    "xpos": ".",
                    "head": 2,
                    "deprel": "punct",
                    "misc": "start_char=39|end_char=40",
                },
            ],
        }
    ],
    schema=schema,
)
print(result)  # YES None
